### ISSUE TITLE
requiring for ckpt files

### ISSUE THREAD

**Issue by K3ats** [KaiyuanZh/OrthogLinearBackdoor#1]
Thanks for open source, can u upload the ckpt files?

**Comment by KaiyuanZh** [comment]
Thank you for your attention and patience. I have uploaded the `ckpt` files as requested. I apologize for the delayed response. Additionally, you can also train the model using `model_train.py` if needed.

**Comment by K3ats** [comment]
Thank you so much for sharing this useful file! It has been very helpful to me.

**Comment by KaiyuanZh** [comment]
No problem 😊
